name: Shell commands

on: [pull_request]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "This is our first github actions workflow file"
      - name: Run linux commands
        run: |
          pwd 
          ls