name: Use of GitHub OIDC

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::365267084374:role/github-actions-role-test 
        aws-region: us-east-1
    - name: setup Terraform CLI
      uses: hashicorp/setup-terraform@v2
    - name: Create resources with terraform commands
      run : |
 #       terraform destroy
        terraform init
        terraform plan
        terraform apply -auto-approve
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync index.html s3://feature-ops-portal-ui